import os
import re
import importlib.util
import sys
from typing import Optional, Any, Dict
from datetime import datetime
from ..config import settings

class FileService:
    def __init__(self):
        self.generated_apis_dir = settings.GENERATED_APIS_DIR
        self._ensure_directory_exists()
    
    def _ensure_directory_exists(self):
        """Ensure the generated APIs directory exists."""
        if not os.path.exists(self.generated_apis_dir):
            os.makedirs(self.generated_apis_dir)
    
    def generate_api_slug(self, user_id: str, api_name: Optional[str] = None) -> str:
        """Generate a unique slug for the API."""
        if api_name:
            # Clean the API name
            slug_base = re.sub(r'[^a-zA-Z0-9_-]', '_', api_name.lower())
        else:
            # Generate timestamp-based slug
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            slug_base = f"api_{timestamp}"
        
        # Combine with user_id
        api_slug = f"{user_id}_{slug_base}"
        
        # Ensure uniqueness
        counter = 1
        original_slug = api_slug
        while self._api_file_exists(api_slug):
            api_slug = f"{original_slug}_{counter}"
            counter += 1
        
        return api_slug
    
    def save_api_code(self, api_slug: str, code: str) -> str:
        """Save generated API code to file."""
        file_path = self._get_api_file_path(api_slug)
        
        # Add metadata header to the file
        header = f'''"""
Generated API: {api_slug}
Generated at: {datetime.now().isoformat()}
This file was automatically generated by AI-Powered API Generator
"""

'''
        
        full_content = header + code
        
        try:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(full_content)
            return file_path
        except Exception as e:
            raise Exception(f"Failed to save API code: {str(e)}")
    
    def load_and_execute_api(self, user_id: str, api_slug: str, 
                           file_bytes: Optional[bytes] = None, 
                           input_data: Optional[Dict[str, Any]] = None) -> Any:
        """Load and execute the generated API."""
        full_slug = f"{user_id}_{api_slug}"
        file_path = self._get_api_file_path(full_slug)
        
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"API not found: {full_slug}")
        
        try:
            # Load the module dynamically
            spec = importlib.util.spec_from_file_location(full_slug, file_path)
            if spec is None or spec.loader is None:
                raise Exception(f"Could not load module spec for {full_slug}")
            
            module = importlib.util.module_from_spec(spec)
            
            # No injection needed - generated APIs can make their own API calls
            
            # Execute the module
            spec.loader.exec_module(module)
            
            # Get the run function
            if not hasattr(module, 'run'):
                raise Exception("Generated API does not have a 'run' function")
            
            run_function = getattr(module, 'run')
            
            # Execute the function
            result = run_function(file_bytes=file_bytes, input_data=input_data)
            
            # Clean up the module from sys.modules if it was added
            if full_slug in sys.modules:
                del sys.modules[full_slug]
            
            return result
            
        except Exception as e:
            raise Exception(f"Failed to execute API {full_slug}: {str(e)}")
    
    def api_exists(self, user_id: str, api_slug: str) -> bool:
        """Check if an API exists."""
        full_slug = f"{user_id}_{api_slug}"
        return self._api_file_exists(full_slug)
    
    def get_user_apis(self, user_id: str) -> list:
        """Get list of APIs for a specific user."""
        apis = []
        if not os.path.exists(self.generated_apis_dir):
            return apis
        
        prefix = f"{user_id}_"
        for filename in os.listdir(self.generated_apis_dir):
            if filename.startswith(prefix) and filename.endswith('.py'):
                api_slug = filename[len(prefix):-3]  # Remove user_id prefix and .py extension
                apis.append({
                    'api_slug': api_slug,
                    'filename': filename,
                    'created_at': self._get_file_creation_time(filename)
                })
        
        return sorted(apis, key=lambda x: x['created_at'], reverse=True)
    
    def delete_api(self, user_id: str, api_slug: str) -> bool:
        """Delete an API file."""
        full_slug = f"{user_id}_{api_slug}"
        file_path = self._get_api_file_path(full_slug)
        
        if os.path.exists(file_path):
            try:
                os.remove(file_path)
                return True
            except Exception:
                return False
        return False
    
    def _api_file_exists(self, api_slug: str) -> bool:
        """Check if API file exists."""
        file_path = self._get_api_file_path(api_slug)
        return os.path.exists(file_path)
    
    def _get_api_file_path(self, api_slug: str) -> str:
        """Get the full file path for an API."""
        return os.path.join(self.generated_apis_dir, f"{api_slug}.py")
    
    def _get_file_creation_time(self, filename: str) -> datetime:
        """Get file creation time."""
        file_path = os.path.join(self.generated_apis_dir, filename)
        try:
            timestamp = os.path.getctime(file_path)
            return datetime.fromtimestamp(timestamp)
        except Exception:
            return datetime.now()

# Global instance
file_service = FileService() 